services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}'
      - 'MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}'
    ports:
      - '27017:27017'

  rabbitmq:
    image: 'rabbitmq:3-management'
    environment:
      - 'RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}'
      - 'RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}'
    ports:
      - '5672:5672'
      - '15672:15672'
