spring.application.name=Home-BankApp
spring.data.mongodb.uri=${MONGODB_LOCAL_URI}

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.example.demo=TRACE

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true